Adding initial GPSSetup project
Vantiq/Contributions pull request #11
Opened 2021-07-20 00:21 UTC by pburma

GPSSetup is a client builder example of how to convert XY image coordinate points to GPS lat/lng points for the CovertCoordinates activity pattern.

=== Instructions ===

- Run the GPSSetup client. 
- Click anywhere on the map to add camera markers
- Use the GPS button on the table to open the Calibration page
- Click Load Image to load a local file into the html canvas
- Move the 4 green squares around to indicate field of view for a camera
- Move the 4 GPS points located on the map to the right around to locate physical location
- Click Submit to save

The GPS and XY coordinates are saved to the cameras type. Once saved to the cameras type a CachedEnriched event can be used to load those values into each memory and then passed into a ConvertCoordinated activity pattern as a downstream event. An example application in the App Builder will look like this:

EventStream(objrec payload) --> SplitBy CameraId --> CachedEnrich cameras --> Transformation --> ConvertCoordinates --> TrackMotion

The Transformation can be very tricky so an example procedure has been included in this project called transformCameraEvents that can be applied to the ConvertCoordinates calibrationKey parameters using the value event.calibrationCoordinates. 

=== Typical Uses ===

To show the results of object recognition data on a map. Object recognition systems will return 4 point bounding box results that indicate the location of an object inside its field of view, which is just an image or a frame from a video. To show where in the real-world that object is located a user can use these web tools to calibrate the camera mapping settings in a simple and easy way. 

Zoning:
It is also possible to use similar UI components to create a Zone (area of interest) in the image. The GPSSetup client can be modified to save and load the 4 points from an image and not include any map points. An object property has to be added to store the Zone for each camera. There is no "Zone" activity pattern so a procedure would need to be written that looks to see if a bounding box or centroid provided by the computer vision results is located inside your zone of interest. The procedure pointInPolygon was added to this project as an example of how to make that calculation.

=== Caveats and Other Notes ===

If the Vantiq extension source is being used it has the ability to upload images periodically or on-demand using a remote query. The Image Load feature can then be replaced by loading the most recent image from the camera of that same name. 

If the Vantiq extension source is not being used it may be possible to load an image from a recent payload from the CVE system otherwise a user will have to manually upload an image. A property was added to the type called "img" which can be used to reference an image to load here but remember if the camera is ever moved a new upload must be made.

2021-07-20 00:50 UTC, pburma commented
![image](https://user-images.githubusercontent.com/11183903/126245570-45528a51-9f49-47f0-84d8-4202965729a8.png)

![image](https://user-images.githubusercontent.com/11183903/126245708-f42890d0-1cdf-414a-a46e-518ab2f883f9.png)

2021-08-19 21:44 UTC, namirfa requested changes
Looks good, most comments are related to code-style.

I tried testing this manually and I think it works as expected, though I'm not confident that I tested it thoroughly enough. It would be great if you could show me a demonstration of how it works so that I can more effectively test edge cases. That will also help me give notes for clarifying the Project Description.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    // But we aren't checking anything else! We could put "Lalala" for the value of x
Is it worth checking that x/y/w/h are all integers, and that fill is a valid hex color string?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    //this.base_image = canvas.toDataURL();
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    // This complicates things a little but but fixes mouse co-ordinate problems
```suggestion
    // This complicates things a little but fixes mouse coordinate problems
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    //fixes a problem where double clicking causes text to get selected on the canvas
```suggestion
    // Fixes a problem where double clicking causes text to get selected on the canvas
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +        console.log(scroll);
What is this logging/is it worth logging? Just wondering if that was left behind from debugging.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            // myState.page.data.camera.zoneConfiguration = [{"zone":"zone1"}]
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +                            console.log(myState.page.topLeftImage);
I'm guessing these log statements are left behind from debugging. Probably better to delete them, unless we want to add logs for each case?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +                    console.log("You are moving shape: "  + i );
```suggestion
                    console.log("You are moving shape: "  + i);
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +                    console.log( i + type);
```suggestion
                    console.log(i + type);
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +                            // code block
Shouldn't there be a default case here, or is this just ignored? Is it worth logging an error or something of the sort?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +
Probably don't need empty lines surrounding this, or at least not the two empty lines after the log.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +        // console.log(this);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +
Don't need so many empty lines

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    // this.shapes.push(shape);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +
Don't need two empty lines, one should be sufficient

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +
Only need one line between method defs

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +
Only need one line between method defs

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +    // console.log("CALLED: CanvasState.prototype.draw");
Probably best to either uncomment this log line, or delete all of the initial "CALLED" logs for each method.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +// It only ever does something if the canvas gets invalidated by our code
```suggestion
// it only ever does something if the canvas gets invalidated by our code
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            // ctx.fillStyle = '#f00';
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            //ctx.globalAlpha = 0.5;
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            // ctx.fillStyle = '#f00';
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            //ctx.globalAlpha = 0.5;
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +            ctx.fill();
The code for `l >= 4` and `l >= 8` is almost identical. Probably could be consolidated in a helper method.

Also, is `l` ever anything but 4 or 8? What happens if it's less than 4?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/client/customCode.js
> +        } while ((element = element.offsetParent));
Any reason why this can't simply be a while loop? Doesn't look like the "do" block affects the outcome of the while condition.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onEnd.js
> +    // clear image
Could be a Vantiq Client thing, but any reason why this code is indented?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +    var page = this;
Ditto - any reason why this code is indented?

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +    //var canvas = $("#callibration-canvas").get(0);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +        //if (page.data.camera.gpsTrack.length > 1 ){
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +        addMarker(latlngtr, "topRightGeo");
Looks like the only difference between the if/else blocks is how the `lat___` variables are defined. Could simplify by  setting them once, and conditionally changing them if necessary.

Then, outside the if block, you only need to call `addMarker` 4 times.

Something like:

```
var latlngbl = page.data.camera.gpsTrack.bottomLeftGeo;
var latlngbr = page.data.camera.gpsTrack.bottomRightGeo;
var latlngtl = page.data.camera.gpsTrack.topLeftGeo;
var latlngtr = page.data.camera.gpsTrack.topRightGeo;

if (jQuery.isEmptyObject(page.data.camera.gpsTrack)) {
    latlngbl = {lat:page.data.camera.geo.coordinates[1] - 0.0001, lng:page.data.camera.geo.coordinates[0] - 0.0001};
    latlngbr = {lat:page.data.camera.geo.coordinates[1] - 0.0001, lng:page.data.camera.geo.coordinates[0] + 0.0001};
    latlngtl = {lat:page.data.camera.geo.coordinates[1] + 0.0001, lng:page.data.camera.geo.coordinates[0] - 0.0001};
    latlngtr = {lat:page.data.camera.geo.coordinates[1] + 0.0001, lng:page.data.camera.geo.coordinates[0] + 0.0001};
}

addMarker(latlngbl, "bottomLeftGeo");
addMarker(latlngbr, "bottomRightGeo");
addMarker(latlngtl, "topLeftGeo");
addMarker(latlngtr, "topRightGeo");
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +        //marker.setMap(map);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +    }
Remove unnecessary new lines between if/else, and inside else blocks. Also change if statements to the following format: 

```if (myCondition) {``` 

(space after `if` and space before open bracket)

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +        }
Ditto for if styling

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/onStart.js
> +        //. then if there are existing plots use them instead
```suggestion
        // then if there are existing plots use them instead
```

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/widgets/Button3523/onClick.js
> +
Remove initial empty lines. Also same question about indentation.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/widgets/Button3524/onClick.js
> +
Remove initial empty lines. Also same question about indentation.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/CameraGPS/widgets/Button3525/onClick.js
> +	client.returnToCallingPage();
Same question about indentation.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/onStart.js
> +
Remove initial empty line. Also same question about indentation.

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/onStart.js
> +        //);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/onStart.js
> +
Remove extra empty line

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/onStart.js
> +        //infoWindow.open(map);
Remove commented code

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/widgets/DataTable492/onButtonClickCallback.js
> +    console.log("Extra: " + extra);
Same question about indentation

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/page/Start/widgets/DataTable492/onButtonClickCallback.js
> +
Remove unnecessary empty lines

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/clients/GPSSetup/controllers/sidebar/widgets/MenuButton4/onClick.js
> +    client.goToPage("Start");
Same question about indentation

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/procedures/submitCamera.vail
> +
Unnecessary empty line

2021-08-19 21:44 UTC, namirfa commented on GPSSetup/procedures/transformCameraEvent.vail
> +    if(detection.label == "person"){
Same comment about `if` codestyling

2021-12-17 20:36 UTC, pburma reviewed
accepted changes

2022-01-05 00:03 UTC, steve-langley reviewed
Some observations...

It doesn't look like the icons/acousticIcon.png or icons/cameraIcon.png Documents are actually checked into the GPSSetup project (at least I couldn't find them)

"ConvertCoordinates" is misspelled a couple of times in the Project Description (once as "CovertCoordinates" and once as "ConvertCoordinated")

Don't take the comments below too seriously - just impressions from someone who really doesn't know what this client is doing...

Is there a reason why there is a DropList on the Start page with only a single item in the list? ("Camera")

Could probably use some more comments. For example, some explanation as to what the CanvasState class in "Custom Code" does.


Maybe add a comment in the "OnClick" event for the Load Image button that explains that "#imageLoader" is found in the StaticHtml named "StaticHtml897" and this is a trick to upload an image file. The event listeners to handle this are in the CameraGPS Page's "On Start" event.

Is the sidebar with "Start" really necessary? The "Back" button on the CameraGPS Page does the same thing.

FWIW "callibration-canvas" should be spelled "calibration-canvas"

2022-01-06 18:10 UTC, zhangevan commented
> The GPS and XY coordinates are saved to the cameras type. Once saved to the cameras type a CachedEnriched event can be used to load those values into each memory and then passed into a ConvertCoordinated activity pattern as a downstream event. An example application in the App Builder will look like this:
> 
> EventStream(objrec payload) --> SplitBy CameraId --> CachedEnrich cameras --> Transformation --> ConvertCoordinates --> TrackMotion

Should we create this App and include it in the contribution to further demonstrate the usage of those coordinates?

2022-02-14 19:43 UTC, rblumer4 approved these changes
May still be missing an icon file.
But this isn't going to be added to the Import dialog, so that can be added in a later PR.

2022-02-14 19:44 UTC, merged