Example of a side-by-side draggable and resortable multiselect field
Vantiq/Contributions pull request #12
Opened 2021-07-20 21:28 UTC by pburma

This is an example of how to add a side-by-side multiselect feature. Especially useful for database operations that use arrays. This example uses css to show the selected vs available list of items. It is also possible to use a this code to create single list for the purposes of manually reordering an array. 

![image](https://user-images.githubusercontent.com/11183903/126396453-caae8c1b-ef5e-4c75-b0cf-194dee148467.png)

![image](https://user-images.githubusercontent.com/11183903/126396486-4cb1fb88-bb4a-458e-a92d-d6bb87583713.png)

The projects includes sample data to load into the multiselect as shown in the screenshots.

2021-07-20 21:28 UTC, pburma commented
![image](https://user-images.githubusercontent.com/11183903/126397814-0899a6fb-872c-4d8f-9c05-4613bb81b84f.png)

2021-08-19 00:05 UTC, namirfa requested changes
Pretty much only requesting some code-style changes.

One question:
Is the desired result here that after dragging/sorting the elements in both fields, that the state should be saved? Seems like this just offers the ability to move stuff around, but if I reload the client everything jumps back to it's original state.

Would be helpful to clarify what the intended use-case would be for this.

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +    });
Needs to be indented

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +    var setLocations = parameters.locations;
Is this supposed to be commented out?

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +
Generally weird indentation here, looks like everything is indented to start which probably isn't necessary.

Code inside function defs should be indented, function defs should all be indented the same, etc...

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +    if(setLocations){
```suggestion
    if (setLocations) {
```

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +    client.select("selected", {}, function(setLocations){
```suggestion
    client.select("selected", {}, function(setLocations) {
```

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +    client.select("locations", {}, function(results){
```suggestion
    client.select("locations", {}, function(results) {
```

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +        results.forEach(function(item, index){
```suggestion
        results.forEach(function(item, index) {
```

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/widgets/Button3527/onClick.js
> +	var list = $('#setLocations li').toArray();
Shouldn't be indented.

2021-08-19 00:05 UTC, namirfa commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/widgets/Button3527/onClick.js
> +    list.forEach(function(item, index){
```suggestion
    list.forEach(function(item, index) {
```

2021-08-19 00:50 UTC, namirfa commented
Also, is there a reason why this is called `MultiSelect1` instead of just `MultiSelect`? Are we expecting to have a `MultiSelect2` and so on?

2021-10-01 17:07 UTC, pburma commented
> Also, is there a reason why this is called `MultiSelect1` instead of just `MultiSelect`? Are we expecting to have a `MultiSelect2` and so on?

Yes, there is a couple different variations on the multiselect and will plan on adding others, maybe as components.

2022-01-04 23:38 UTC, zhangevan commented
@pburma After importing the project and tried it out. I ran into a bug where the left list is completely empty after moving a few items to the right list:
![image](https://user-images.githubusercontent.com/34021370/148138435-b58dc216-0565-49e3-8473-5e9589e8544f.png)

2022-01-05 00:24 UTC, steve-langley reviewed
I didn't see the error @zhangevan did, it seemed to work for me. My only comment would be that I think it might be helpful to pad it out with some comments so the user knows what you are doing. In particular it might be good to note that this is based on the "sortable" feature in JQuery-UI (with maybe a link to the doc).

Otherwise a naive user might not have a clue how all this is working, since there doesn't seem to be any code in the example that actually implements the sortability functionality.

2022-01-05 00:25 UTC, steve-langley commented on MultiSelect1/clients/MultiSelect1/controllers/page/Start/onStart.js
> +        function containsObject(obj, list) {
Little indenting problem here that makes the code harder to read.

2022-01-05 20:04 UTC, zhangevan commented
Don't worry about the bug I reported yesterday. I realized I was using an old version of Chrome (version 75) for other testing purposes.  I don't see the problem on other browsers like Edge and Firefox.

2022-02-03 22:43 UTC, rblumer4 approved these changes
Looks like the only thing holding up this PR is a lack of comments.
But it works, so we can merge it in without that.

2022-02-03 22:44 UTC, merged