New contributions project: TrackingRegion
Vantiq/Contributions pull request #26
Opened 2023-10-23 18:09 UTC by zhangevan

This project contains 4 client components that you can use in your clients.

Client Components:
com.vantiq.component.ui.BoundaryEditor - A eitor for specifying boundary (an array of 4 points) over an selected image. com.vantiq.component.ui.DirectionDistanceEditor - A editor for editing "distance" or "direction" property of a TrackingRegion. com.vantiq.component.ui.ConvertCoordinates - A editor for editing "convertionSepcification" property of a TrackingRegion. com.vantiq.component.ui.TrackingRegionEditor - A Client component to create/view/edit a tracking region. It use above three client components to edit its properties. 

Using the Tracking Region Editor
You can run com.vantiq.component.ui.TrackingRegionEditor as a normal Client to create/edit/view tracking regions. You can also embed the editor as a component to your Client. See TestTrackingRegion as an example. The TrackingRegionEditor component's toolbar buttons are hidden by setting its hideToolbar property to true.

2023-10-24 19:40 UTC, rblumer4 requested changes
Did not review the code.
Just reviewed the README and ran the clients.   Sent one stacktrace from ConvertCoordinates via email...

2023-10-24 19:40 UTC, rblumer4 commented on TrackingRegion/README.md
> +You can also embed the editor as a component to your Client. See TestTrackingRegion as an example. The TrackingRegionEditor component's toolbar buttons are hidden by setting its hideToolbar property
add some italics to highlight settings
```suggestion
You can also embed the editor as a component to your Client. See _TestTrackingRegion_ as an example. The TrackingRegionEditor component's toolbar buttons are hidden by setting its _hideToolbar_ property to `true`.
```

2023-10-24 19:40 UTC, rblumer4 commented on TrackingRegion/README.md
> +* com.vantiq.component.ui.TrackingRegionEditor - A Client component to create/view/edit a tracking region. It use above three client components to edit its properties.
typo: eitor -> editor  
typo A -> An   (on all 4 lines)
Also, make component names bold or italic, e.g.
```suggestion
* **com.vantiq.component.ui.BoundaryEditor** - An editor for specifying boundary (an array of 4 points) over an selected image.
* **com.vantiq.component.ui.DirectionDistanceEditor** - An editor for editing "distance" or "direction" property of a TrackingRegion.
* **com.vantiq.component.ui.ConvertCoordinates** - An editor for editing "convertionSepcification" property of a TrackingRegion.
* **com.vantiq.component.ui.TrackingRegionEditor** - A Client component to create/view/edit a tracking region. It use above three client components to edit its properties.  
```

2023-10-24 19:40 UTC, rblumer4 commented on TrackingRegion/projects/TrackingRegion.json
> +    "description" : "This project  contains 4 client components that you can use in your clients.\n\n### Client Components: ###\n* com.vantiq.component.ui.BoundaryEditor - A eitor for specifying boun
This is the same as the README.md, so need to fix the same typos & add formatting here.

2023-10-24 23:05 UTC, rblumer4 approved these changes, later dismissed
LGTM, found a couple more typos
Did you fix the stacktrace or should I file a bug about that?

2023-10-24 23:05 UTC, rblumer4 commented on TrackingRegion/README.md
> +    * **convertedCoordinates** -- A set of 4 porints converted from 4 points of **imageCoordinates" on the output coordinates.  Output coordinates can be set of latitude and longitude coordinates on
typo: porints to points
set -> a set
```suggestion
    * **convertedCoordinates** -- A set of 4 points converted from 4 points of **imageCoordinates" on the output coordinates.  Output coordinates can be a set of latitude and longitude coordinates on a map.
```

2023-10-24 23:05 UTC, rblumer4 commented on TrackingRegion/README.md
> +* **converstionOnly** -- a boolean
typo?
```suggestion
* **conversionOnly** -- a boolean 
```

2023-10-24 23:05 UTC, rblumer4 commented on TrackingRegion/projects/TrackingRegion.json
> +    "description" : "This project  contains 4 client components that provides a grapical interface for editing a Tracking Region.\n\n### About Tracking Region ###\nA tracking region represents a name
typo: porints -> points
set -> a set
converstionOnly -> conversionOnly
```suggestion
    "description" : "This project  contains 4 client components that provides a grapical interface for editing a Tracking Region.\n\n### About Tracking Region ###\nA tracking region represents a named area in a coordinate space.\nTracking regions have the following properties:\n\n* **name** -- this is the name of the tracking region.\n* **boundary** -- this is an Object that contains a list of (at most 4) points that comprise the boundary of the region.\n* **distance** -- this is an Object containing the following properties:\n    * **points** -- a list of two points\n    * **distance** -- the distance between these two points\n* **direction** -- this is an Object containing the following properties\n    * **points** -- a list of two points\n    * **direction** -- the direction (compass degrees between 0 and 360) that movement from the\nfirst point to the second represents.\n* **conversionOnly** -- a boolean \n* **conversionSpecification** -- this is an Object defines the conversion between 2 coordinates. It containing the following properties\n    * **imageCoordinates** -- A set of 4 points in input coordinates with are 4 corners of image used by **boundary**, **distance**, and **direction**.\n    * **convertedCoordinates** -- A set of 4 points converted from 4 points of **imageCoordinates\" on the output coordinates.  Output coordinates can be a set of latitude and longitude coordinates on a map.\n\n### Client Components: ###\n* **com.vantiq.component.ui.BoundaryEditor** - An editor for specifying boundary (an array of 4 points) over an selected image.\n\n![Boundary Editor](docs/boundary_editor.JPG)\n\n* **com.vantiq.component.ui.DirectionDistanceEditor** - An editor for editing \"distance\" or \"direction\" property of a TrackingRegion.\n\n![Distance/Direction Editor](docs/distance_editor.JPG)\n* **com.vantiq.component.ui.ConvertCoordinates** - An editor for editing \"convertionSepcification\" property of a TrackingRegion.\n\n![ConvertCoordinates Editor](docs/convert_editor.JPG)\n\n* **com.vantiq.component.ui.TrackingRegionEditor** - A Client component to create/view/edit a tracking region. It use above three client components to edit its properties.  \n\n\n![TrackingRegion Editor](docs/region_editor.JPG)\n\n### Using the Tracking Region Editor ###\nYou can run com.vantiq.component.ui.TrackingRegionEditor as a normal Client to create/edit/view tracking regions.\n\nYou can also embed the editor as a component to your Client. See _TestTrackingRegion_ as an example. The TrackingRegionEditor component's toolbar buttons are hidden by setting its _hideToolbar_ property to `true`.",
```

2023-10-25 00:03 UTC, zhangevan commented
@rblumer4 thanks for the review. the stacktrace was fixed in 1.38 by Steve a while ago.

2023-10-25 00:07 UTC, zhangevan commented on TrackingRegion/README.md
> +* **converstionOnly** -- a boolean
yes, typo.

2023-10-25 18:32 UTC, rblumer4 approved these changes
LGTM
stacktrace is now fixed in standalone ConvertCoordinates client

2023-10-25 19:19 UTC, merged