Added MS Face APIs
Vantiq/Contributions pull request #3
Opened 2018-12-20 13:00 UTC by bruden01

This is a set of Microsoft Face API's from Azure Cognitive Services.  It provides a series of functions for performing face detection (gender, emotion, accessories, etc...), face recognition, as well as training and grouping.

2018-12-20 18:51 UTC, rblumer4 commented on MSFaceAPIs/projects/MSFaceAPIs.json
> +    "description" : "MICROSOFT FACE API'S\n\nIn order to use these API's you will need to set up the Azure FaceAPI and obtain a subscription key.\n\nThe modify the faceapi source in VANTIQ and set th
Typos:  The -> Then, that -> since
```suggestion
     "description" : "MICROSOFT FACE API'S\n\nIn order to use these API's you will need to set up the Azure FaceAPI and obtain a subscription key.\n\nThen modify the faceapi source in VANTIQ and set the key\n{\"Ocp-Apim-Subscription-Key\":\"<Your Subscription Key>\"}\n\nIf all is setup correctly you should be able to run the 3 procedures to the right in order\n\nFor more info on the face api visit:\n\nhttps://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236\n\nThis is a collection of API connection to Azure cognitive services.\n\nSpecifically the FACE API\n\nAPI's\n-------------------------\nFaceDetect:\nFind faces in an image and return attributes (age, gender, facialHair, glasses, emotion, hair, makeup, accessories)\n\nFaceIdentify:\nFor a face found in FaceDetect see if there are any matches against a particular person group. (collection of people and faces)\n\nFaceListList:\nList faces added to the facelist\n\nPersonGroupCreate:\nCreate a person group\n\nPersonGroupDelete:\nDelete a person group\n\nPersonGroupGetTrainingStatus:\nGet the training status of a person group\n\nPersonGroupList:\nList all person groups\n\nPersonGroupPersonCreate:\nCreate a person in a person group\n\nPersonGroupPersonAddFace:\nAdd a face to a person in the person group\n\n\nPersonGroupPersonDelete:\nDelete a person from the person group\n\nPersonGroupPersonGet:\nGet the details of a person in a person group\n\nPersonGroupPersonGetFace:\nRetrieve person face information. The persisted person face is specified by its personGroupId, personId and persistedFaceId.\n\nPersonGroupPersonList:\nList all persons’ information in the specified person group, including personId, name, userData and persistedFaceIds of registered person faces.\n\nPersonGroupTrain:\nSubmit a person group training task. Training is a crucial step since only a trained person group can be used by Face - Identify. \n\n\n\n\n\n",
```

2018-12-20 19:29 UTC, JakeSchmitz requested changes
One request for consistency. Can you capitalize the first letter of the service name in each procedure, and lowercase the first letter of the procedure name? This is consistent with all of the built ins VANTIQ has added. E.g: msFaceAPI.FaceDetect -> MSFaceAPI.faceDetect

2018-12-21 15:50 UTC, bruden01 commented
Ok..  Changes to procedures have been made per @JakeSchmitz

2018-12-21 21:30 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.createGroupAndPerson.vail
> +var faceResult = msFaceAPI.PersonGroupPersonAddFace("friend_group", obj.personId, "https://cdn.pixabay.com/photo/2016/08/24/14/32/man-1617126_1280.jpg", "Trip to the mountains", targetFace)
This is now using the wrong procedure/ service name. Looks like there are a lot of these references that need to be fixed now that you've changed the capitalization of the procedure and service names

2018-12-21 21:32 UTC, JakeSchmitz requested changes
Marked some spots where names need to be fixed to reflect capitalization changes

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.createGroupAndPerson.vail
> +msFaceAPI.PersonGroupTrain("friend_group")
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.identifyFace.vail
> +var faceResults = msFaceAPI.FaceDetect("https://cdn.pixabay.com/photo/2016/08/24/14/32/man-1617126_1280.jpg")
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.identifyFace.vail
> +	var person = msFaceAPI.PersonGroupPersonGet("friend_group", item.personId )
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.createGroupAndPerson.vail
> +msFaceAPI.PersonGroupCreate("friend_group", "Friends", "Person group identifies friends")
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.createGroupAndPerson.vail
> +obj.personId = personResult[0].body.personId
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.createGroupAndPerson.vail
> +var faceResults = msFaceAPI.FaceDetect("https://cdn.pixabay.com/photo/2016/08/24/14/32/man-1617126_1280.jpg")
here

2018-12-21 21:32 UTC, JakeSchmitz commented on MSFaceAPIs/procedures/facedemo.resetDemo.vail
> +msFaceAPI.PersonGroupDelete("friend_group")
here

2018-12-26 16:47 UTC, bruden01 commented
Ok. I think I fixed the remaining issues with the demo procedures not pointing to the right API's after I changed the case of the procedure names. Let me know if there are any other issues.

2019-01-03 15:08 UTC, bruden01 commented
is this ready to go or am I still missing something?

2019-01-04 01:14 UTC, JakeSchmitz commented
One last issue is the file names no longer match the procedure names. Sorry I didn't make that clear in my last comment.

2019-01-04 13:24 UTC, bruden01 commented
how do I fix that? The export procedure names them.  Or do you mean
manually?

On Thu, Jan 3, 2019 at 8:14 PM Jacob Schmitz <notifications@github.com>
wrote:

> One last issue is the file names no longer match the procedure names.
> Sorry I didn't make that clear in my last comment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vantiq/Contributions/pull/3#issuecomment-451329022>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACbhr7UwOx7jNd0kd-Kn9FsyAG4zTbd7ks5u_qsEgaJpZM4ZcJjT>
> .
>

2019-01-04 16:52 UTC, rblumer4 commented
If you re-export the procedures after the rename, the files should get the new name.
If you renamed them in the existing export directory, rather than in your namespace, you could import the changed files & then re-export them and the procedure files should get the new names...
To get them renamed in GIT, you'd have to manually delete the old files (_git rm_), do the export, then add the new files (_git add_) and commit them.

2019-10-31 15:42 UTC, bruden01 commented
I think this is ready now.

2019-11-05 23:38 UTC, JakeSchmitz approved these changes
LGTM

2019-11-14 14:39 UTC, merged