Adding VisionDemo project
Vantiq/Contributions pull request #4
Opened 2019-10-23 17:44 UTC by pburma

VisionDemo, collection of small examples for TensorFlow and VisionScripts.

2019-11-05 23:39 UTC, JakeSchmitz requested changes
Will this work with the version running on dev currently, or does this require 1.27?

2019-11-14 15:09 UTC, pburma commented
It was built on 1.26.

2019-11-14 16:43 UTC, JakeSchmitz submitted a review, later dismissed
LGTM, just one style comment to fix before merging

2019-11-14 16:43 UTC, JakeSchmitz commented on VisionDemo/procedures/vsExample.vail
> +    // Create the script
For consistency with your other procedures, can you un-indent this?

2020-05-13 16:18 UTC, JakeSchmitz approved these changes
Hey @pburma really sorry this never got merged in. I've approved it now. If you want to test it out again on 1.28 feel free, or merge this in directly.

2021-04-07 17:09 UTC, JakeSchmitz commented
Closing because this was taken over by our intern @jvic12 and finally merged into master (in time for the release of 1.31)

2021-04-07 17:09 UTC, closed without merging